### ISSUE TITLE
Datos de Carga en Pantalla de Asiento

### ISSUE THREAD

**Issue by trancemeister75** [QADM/SCG#1]
En la creación y modificación de una cuenta, debe de mostrar todos los datos de carga para esa pantalla, es decir , hace falta el de la cuenta mayor, catalgo auxiliar y nodo, ademas de que debe de ser una caja de selección de valores para codificación, tipo de cuenta, naturaleza, nodo y cuenta mayor, y obviamente validar que el catalogo auxiliar que se le quiera añadir si se encuentre en la aplicació, para eso puede agregarse alguna solución como las que ya tiene implementadas la aplicación

**Comment by miguelcanm** [comment]
Actualmente, al momento de editar o crear una clase, nos obliga a que exista un catálogo auxiliar (categoría), lo cual es incorrecto, debe permitir que no exista forzosamente un catalogo auxiliar ligado a la cuenta.

En la actualización de la cuenta todos los campos no se actualizan correctamente (ejemplo categoría)

En la creación y edición de la cuenta el tipo de cuenta debe ser totalizadora, acumulativa y de registro, no las que se encuentran actualmente
