### ISSUE TITLE
Poliza Manual

### ISSUE THREAD

**Issue by trancemeister75** [QADM/SCG#10]
Crear polizas manuales

**Comment by trancemeister75** [comment]
Bueño pues este issue se resuelve con el issue #19

**Comment by miguelcanm** [comment]
@obanos te encargo de favor que esto lo cheques con @smisis, ya que ella esta creando transacciones manuales, en teoría vendría siendo casi lo mismo, te debe de explicar @valerossi, cualquier duda me puedes preguntar

**Comment by miguelcanm** [comment]
Realmente este bug se cumple con las transacciones manuales, por lo cual se cierra
