### ISSUE TITLE
Carga de presupuesto

### ISSUE THREAD

**Issue by miguelcanm** [QADM/SCG#125]
Cuando se carga el presupuesto pones un código de transacción, en el cual al final indicas el mes, es decir, 1,2,3... favor de cambiar ese código, es decir, en vez de 1 que diga 01,02,03, así hasta el 12

**Comment by trancemeister75** [comment]
@jrrmerlin ya lo resolvio

**Comment by miguelcanm** [comment]
@jrrmerlin he revisado el de ingresos y ya lo hace, estoy seguro que el de ingresos tambien lo hace correctamente, sin embargo por el problema que existe actualmente para subir el egreso no puedo dar por cerrado este bug hasta que lo vea

**Comment by miguelcanm** [comment]
Se verifico y es correcto
