### ISSUE TITLE
Transaccion Manual

### ISSUE THREAD

**Issue by trancemeister75** [QADM/SCG#19]
Poder realizar la transacción manual

**Comment by trancemeister75** [comment]
Bueño x @valerossi tambien esta asignado como developa

**Comment by trancemeister75** [comment]
Se cierra temporalmente por indefinicion, autorizado por @golivera44

**Comment by miguelcanm** [comment]
Al tener claro los campos donde se guardará la información, se abre de nuevo este issue, sin embargo, por carga de trabajo, se asigna a @smisis

**Comment by miguelcanm** [comment]
Se ha probado y queda resuelto
