### ISSUE TITLE
Niveles

### ISSUE THREAD

**Issue by trancemeister75** [QADM/SCG#2]
Cuando estoy eligiendo un nivel en cualquier pantalla que aplique este valor, solo me deben de aparecer los niveles relacionados con esa pantalla, caso de loss tags, organizaciones, projectos, etc

**Comment by miguelcanm** [comment]
Aquí de favor @RaulBer solo verificar que en la creación de un Tag, solo aparezcan los niveles que correspondan a la clasificación que se selecciono, se que me has dicho que no se puedo, pero en caso de que sea así justificar el porque no se pude.
