### ISSUE TITLE
Visualización de la poliza

### ISSUE THREAD

**Issue by miguelcanm** [QADM/SCG#50]
Cambiar la visualización de las pólizas una vez que el diseño quede aprobado.

**Comment by trancemeister75** [comment]
Se asigna a @obanos por etapa de pruebas

**Comment by miguelcanm** [comment]
@obanos te encargo poner las claves presupuestales a las que afectas como habiamos quedado antes y el detalle que te hace falta por favor

**Comment by miguelcanm** [comment]
Corrección de bug

**Comment by miguelcanm** [comment]
Corrección de bug
