### ISSUE TITLE
Eliminar descripciones

### ISSUE THREAD

**Issue by miguelcanm** [QADM/SCG#58]
Eliminar todas las descripciones de la tabla ACCTG_TRANS_PRESUPUESTAL, y solo dejar los ids correspondientes

**Comment by miguelcanm** [comment]
Lo que me refiero aquí @jrrmerlin es que elimines las columnas de descripción dentro de esta tabla

**Comment by jrrmerlin** [comment]
En el XML de la tabla ya no estan estas columnas, para que estas se puedan verificar seria necesario borrar la tabla y hacer un make-base-entities. En caso de no ser posible por la presencia de datos, se recomienda borrar via SQL estos campos.
