### ISSUE TITLE
Edicion de Proyecto

### ISSUE THREAD

**Issue by trancemeister75** [QADM/SCG#8]
Cuando edito un proyecto no me respeta los datos iniciale y si le realizo algun cambio, tampoco lo realiza correctamente

**Comment by trancemeister75** [comment]
Se reasigna a @RaulBer porque tenia dependencia con @smisis

**Comment by miguelcanm** [comment]
Favor de verificar porque no se ha resuelto

**Comment by miguelcanm** [comment]
Me muestra otro nivel por ejemplo
